sudo: required
language: python
python:
 - 3.7.5
services:
 - docker
install: pip install -r app/requirements/requirements.txt
script: python manage.py test
before_deploy:
 - docker build -t jaimeviloria/scraper:$TRAVIS_TAG .
deploy:
 provider: script
 script: deploy/hub.sh
 on:
   tags: true
branches:
  only:
    - master
    - dev
